# Generated by Django 5.0.3 on 2026-01-09 10:11

import book_movie_ticket_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_movie_ticket_app', '0002_showtime_ticket_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=book_movie_ticket_app.models.movie_poster_upload_path, verbose_name='Ảnh bìa'),
        ),
    ]
